# This workflow will test a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Unit tests with Maven

on:
  push:
    branches: [main]
    paths:
      - 'example-java/**'
  pull_request:
    branches: [main]
    paths:
      - 'example-java/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # step 1 - clone project
    - name: Checkout the repository
      uses: actions/checkout@v4

    # step 2 - provide java
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    # step 3 - run tests
    - name: Test with Maven
      run: |
        cd example-java
        mvn -B test --file pom.xml

